[tool.poetry]
package-mode = false
name = "cantus-ultimus"

[tool.poetry.dependencies]
python = "^3.12"
celery = "5.4.0"
django = "5.0.6"
django-celery-results = "2.5.1"
djangorestframework = "3.15.1"
gunicorn = "22.0.0"
lxml = "5.2.2"
markdown = "3.6"
psycopg = "3.1.19"
requests = "2.31.0"
solrpy = "1.0.0"

[tool.poetry.group.debug]
optional = true

[tool.poetry.group.debug.dependencies]
django-extensions = "3.2.3"
Werkzeug = "3.0.3"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
mypy = "^1.10.0"
pylint = "^3.1.0"
lxml-stubs = "^0.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
