apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cantaloupe-images-pvc
  namespace: cantus-ultimus
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard