apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-staging
  namespace: cantus-ultimus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-staging
  template:
    metadata:
      labels:
        app: nginx-staging
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: nginx
        image: ghcr.io/ddmal/cantus-nginx:main-latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: nginx-config-staging
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: manifests
          mountPath: /code/manifests
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
      volumes:
      - name: manifests
        persistentVolumeClaim:
          claimName: cantaloupe-manifests-staging-pvc
