apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cantus-ingress-staging
  namespace: cantus-ultimus
spec:
  rules:
  - host: cantus.staging.simssa.ca
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-staging
            port:
              number: 8000
