apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: cantus-ultimus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: rabbitmq
        image: ghcr.io/ddmal/cantus-rabbitmq:main-latest
        ports:
        - containerPort: 5672
        envFrom:
        - configMapRef:
            name: rabbitmq-config
        env:
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_PASS
        readinessProbe:
          exec:
            command: ["rabbitmq-diagnostics", "ping"]
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 5
        livenessProbe:
          exec:
            command: ["rabbitmq-diagnostics", "ping"]
          initialDelaySeconds: 60
          periodSeconds: 20
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "512Mi"