apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: cantus-ultimus
type: Opaque
stringData:
  # Must match RABBIT_PASSWORD in k8s/cantus-ultimus/app/secret.yaml
  RABBITMQ_DEFAULT_PASS: "<value>"