apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solr-data-pvc
  namespace: cantus-ultimus
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path