apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: cantus-ultimus-staging
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"ghcr.io":{"username":"<github-username>","password":"<placeholder>","auth":"<base64 of github-username:<placeholder>>"}}}'