apiVersion: v1
kind: Secret
metadata:
  name: app-secret-staging
  namespace: cantus-ultimus
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "<value>"
  POSTGRES_PASSWORD: "<value>"
  RABBIT_PASSWORD: "<value>"