apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solr-data-staging-pvc
  namespace: cantus-ultimus
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1500Mi
  storageClassName: local-path