apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solr-data-pvc
  namespace: cantus-ultimus-staging
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path