# Generated by Django 5.0.7 on 2026-05-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cantusdata", "0005_manuscript_viewer_warning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manuscript",
            name="date",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
