# Generated by Django 6.0.5 on 2026-08-20 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cantusdata", "0006_alter_manuscript_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MEISubmission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending review"),
                            ("PUBLISHED", "Published"),
                            ("CORRECTION_REQUESTED", "Correction requested"),
                            ("REFUSED", "Refused"),
                            ("SUPERSEDED", "Superseded by a newer submission"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "folio_number",
                    models.CharField(
                        help_text="The canonical folio number, as resolved against the Folio table.",
                        max_length=50,
                    ),
                ),
                (
                    "mei",
                    models.TextField(
                        help_text="The MEI document, exactly as submitted."
                    ),
                ),
                ("content_sha256", models.CharField(editable=False, max_length=64)),
                (
                    "submitter",
                    models.CharField(
                        help_text="Username of the submitting user, as asserted by the submitting system.",
                        max_length=150,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="The submitter's note, if any."
                    ),
                ),
                (
                    "review_note",
                    models.TextField(
                        blank=True,
                        help_text="Shown to the submitter. Required when requesting a correction or refusing a submission.",
                    ),
                ),
                (
                    "published_path",
                    models.CharField(
                        blank=True,
                        help_text="Where the MEI was written under MEI_FILES_DIR when published.",
                        max_length=512,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "folio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cantusdata.folio",
                    ),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cantusdata.manuscript",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_mei_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "PENDING",
                                    "PUBLISHED",
                                    "CORRECTION_REQUESTED",
                                    "REFUSED",
                                    "SUPERSEDED",
                                ],
                            )
                        ),
                        name="mei_submission_status",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "PENDING")),
                        fields=("manuscript", "folio_number", "content_sha256"),
                        name="unique_pending_mei_submission",
                    ),
                ],
            },
        ),
    ]
