apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-cantus-ultimus
  namespace: postgres
spec:
  serviceName: postgres-cantus-ultimus
  replicas: 1
  selector:
    matchLabels:
      app: postgres-cantus-ultimus
  template:
    metadata:
      labels:
        app: postgres-cantus-ultimus
    spec:
      tolerations:
      - effect: NoSchedule
        key: workload
        operator: Equal
        value: database
      containers:
      - name: postgres
        image: postgres:14
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-cantus-ultimus-config
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-cantus-ultimus-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "cantus_admin", "-d", "cantus_db"]
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 5
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "cantus_admin", "-d", "cantus_db"]
          initialDelaySeconds: 30
          periodSeconds: 20
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "2Gi"
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-cantus-ultimus-pvc