apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-staging
  namespace: cantus-ultimus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-staging
  template:
    metadata:
      labels:
        app: rabbitmq-staging
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.11
        ports:
        - containerPort: 5672
        envFrom:
        - configMapRef:
            name: rabbitmq-config-staging
        env:
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret-staging
              key: RABBITMQ_DEFAULT_PASS
        readinessProbe:
          exec:
            command: ["rabbitmq-diagnostics", "ping"]
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 5
        livenessProbe:
          exec:
            command: ["rabbitmq-diagnostics", "ping"]
          initialDelaySeconds: 60
          periodSeconds: 20
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
