apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: cantus-ultimus-staging
type: Opaque
stringData:
  # Must match RABBIT_PASSWORD in app/secret.yaml
  RABBITMQ_DEFAULT_PASS: "<value>"