apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret-staging
  namespace: cantus-ultimus
type: Opaque
stringData:
  # Must match RABBIT_PASSWORD in app/secret.yaml
  RABBITMQ_DEFAULT_PASS: "<value>"