apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-cantus-ultimus-staging-pvc
  namespace: postgres
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path