apiVersion: v1
kind: Service
metadata:
  name: postgres-cantus-ultimus-staging
  namespace: postgres
spec:
  selector:
    app: postgres-cantus-ultimus-staging
  ports:
  - port: 5432
    targetPort: 5432