apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-cantus-ultimus-staging
  namespace: postgres
spec:
  serviceName: postgres-cantus-ultimus-staging
  replicas: 1
  selector:
    matchLabels:
      app: postgres-cantus-ultimus-staging
  template:
    metadata:
      labels:
        app: postgres-cantus-ultimus-staging
    spec:
      tolerations:
      - effect: NoSchedule
        key: workload
        operator: Equal
        value: database
      containers:
      - name: postgres
        image: postgres:14
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-cantus-ultimus-staging-config
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-cantus-ultimus-staging-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "cantus_admin", "-d", "cantus_db_staging"]
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 5
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "cantus_admin", "-d", "cantus_db_staging"]
          initialDelaySeconds: 30
          periodSeconds: 20
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-cantus-ultimus-staging-pvc