apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: cantus-ultimus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: app
        image: ghcr.io/ddmal/cantus-app:main-latest
        imagePullPolicy: Always
        command: ["/code/django-config.sh"]
        ports:
        - containerPort: 8001
        envFrom:
        - configMapRef:
            name: app-config
        env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DJANGO_SECRET_KEY
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: POSTGRES_PASSWORD
        - name: RABBIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: RABBIT_PASSWORD
        readinessProbe:
          tcpSocket:
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 6
        livenessProbe:
          tcpSocket:
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 20
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "2"
            memory: "2Gi"