apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mei-files-pvc
  namespace: cantus-ultimus
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: mei-files-pv
  resources:
    requests:
      storage: 20Gi
