name: unit-tests
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
  run-tests:
    runs-on: ubuntu-latest
    env:
      POSTGRES_PASSWORD: supersecurepassword99
      RABBIT_PASSWORD: supersecurepassword88
    steps:
      - uses: actions/checkout@v3
      - run: docker-compose up -d
      - run: docker-compose exec -T app python runtests.py cantusdata.test.core