name: unit-tests
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo POSTGRES_PASSWORD=supersecurepassword99 >> .env
      - run: docker-compose up -d
      - run: docker-compose exec -T app python runtests.py cantusdata.test.core
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable